name: general_app_package
description: "a package for general app development includes basic translations, themes, and widgets"
version: 0.0.1
homepage: https://github.com/Vicky-Yunitrish-studio/general_app_package.git

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
